INSERT INTO `#dbprefix#langs` (`lang_id`, `term`) VALUES
(1, 'Unknown provider or incorrect URL. Please try again.'),
(2, 'This URL is invalid or the video is removed by the provider.'),
(3, 'All Media Feed'),
(4, 'Video Feed'),
(5, 'Music Feed'),
(6, 'Images Feed'),
(7, 'Show sidebar'),
(8, 'Search videos'),
(9, 'Visitor'),
(10, 'Google login'),
(11, 'Google'),
(12, 'Login'),
(13, 'User & pass'),
(14, 'Forgot password'),
(15, 'Recover'),
(16, 'Classic registration'),
(17, 'Change language'),
(18, 'Hide'),
(19, 'Video Channels'),
(20, 'No homeblocks defined by administrator.'),
(21, 'New Media'),
(22, 'Recent'),
(23, 'Most Viewed'),
(24, 'Featured'),
(25, 'Most Liked'),
(26, 'Most Commented'),
(27, 'New users'),
(28, 'Next video starting soon'),
(29, '404'),
(30, 'oops! page not found'),
(31, 'Back to home'),
(32, 'Sign in to Your Account'),
(33, 'Email'),
(34, 'Email address'),
(35, 'Password'),
(36, 'forgot your password?'),
(37, 'Your Password'),
(38, 'Sign in'),
(39, 'Upload video'),
(40, 'Upload'),
(41, 'Web video'),
(42, 'Music'),
(43, 'Picture'),
(44, 'My Media'),
(45, 'Likes'),
(46, 'Notifications'),
(47, 'New Playlist'),
(48, 'Playlists'),
(49, 'Logout'),
(50, 'My Profile'),
(51, 'Create playlist'),
(52, 'Manage playlists'),
(53, 'Manage likes'),
(54, 'Manage videos'),
(55, 'Videos'),
(56, 'Members'),
(57, 'Video views'),
(58, 'Video likes'),
(59, 'Comments'),
(60, 'Reports'),
(61, 'Update settings'),
(62, 'Facebook fans'),
(63, 'Category:'),
(64, 'Choose a category:'),
(65, 'Sorry but there are no results.'),
(66, 'Title'),
(67, 'Your channel''s title'),
(68, 'Select channel:'),
(69, 'Warning: No channels.'),
(70, 'Description'),
(71, 'Channel image'),
(72, 'Create channel'),
(73, 'Thumb'),
(74, 'Channel'),
(75, 'Delete selected'),
(76, 'Delete'),
(77, 'Edit'),
(78, 'View'),
(79, 'Select only if you wish to change the image'),
(80, 'Update channel'),
(81, 'Music Channels'),
(82, 'Image Categories'),
(83, 'Choose owner:'),
(84, 'First'),
(85, 'Last'),
(86, 'Video'),
(87, 'by'),
(88, 'views'),
(89, 'It''s you'),
(90, 'Like'),
(91, 'Dislike'),
(92, 'Add To'),
(93, 'Report video'),
(94, 'Report'),
(95, 'Reason for reporting'),
(96, 'Video not playing'),
(97, 'Wrong title/description'),
(98, 'Video is offensive'),
(99, 'Video is restricted'),
(100, 'Copyrighted material'),
(101, 'Details of the report'),
(102, 'Send report'),
(103, 'Add to playlist(s)'),
(104, 'You have no playlists that don''t contain this video'),
(105, 'Uploaded'),
(106, 'Link to video'),
(107, 'Embed this video as 480x360'),
(108, 'Embed this video as 640x480'),
(109, 'Write your comment'),
(110, 'Choose Password'),
(111, 'City'),
(112, 'Country'),
(113, 'Avatar'),
(114, 'Duration'),
(115, 'Unpublish selected'),
(116, 'Unpublish'),
(117, 'Feature video'),
(118, 'Permanently delete videos'),
(119, 'Permanently delete video'),
(120, 'Publish video'),
(121, 'Subscribe'),
(122, 'Please login in order to report media.'),
(123, 'Please login in order to collect videos.'),
(124, 'Click to add a subscription'),
(125, 'share'),
(126, 'Share a melody'),
(127, 'Title:'),
(128, 'Duration:'),
(129, 'Music category:'),
(130, 'Description:'),
(131, 'Tags:'),
(132, 'Visibility'),
(133, 'Users only'),
(134, 'Everybody'),
(135, 'NSFW:'),
(136, 'Not safe'),
(137, 'Safe'),
(138, 'Waiting for upload'),
(139, 'created successfully.'),
(140, 'Manage media.'),
(141, 'Browse'),
(142, 'Browse Description'),
(143, 'Loading the player...'),
(144, 'Import selected'),
(145, 'change'),
(146, 'About'),
(147, 'Edit your details'),
(148, 'Last login:'),
(149, 'Registered:'),
(150, 'Sort'),
(151, 'All activity'),
(152, 'Videos shared'),
(153, 'Liked videos'),
(154, 'Watched'),
(155, 'Watched videos'),
(156, 'watched a video'),
(157, 'shared a video'),
(158, 'Change picture'),
(159, 'Upload avatar'),
(160, 'Change cover (1170px/315px)'),
(161, 'Upload cover'),
(162, 'Change password'),
(163, 'Change profile data'),
(164, 'Name'),
(165, 'About you'),
(166, 'Gender'),
(167, 'Male'),
(168, 'Female'),
(169, 'Facebook'),
(170, 'my.profile.username'),
(171, 'Without'),
(172, 'Google Plus'),
(173, 'my.google.id'),
(174, 'Twitter'),
(175, 'my.twitter.username'),
(176, 'Save changes'),
(177, 'Share a video'),
(178, 'uploaded successfully.'),
(179, 'This video will be available after conversion.'),
(180, 'Filter results'),
(181, 'This Week'),
(182, 'All'),
(183, 'This Month'),
(184, 'This Year'),
(185, 'registration'),
(186, 'Create a new Account'),
(187, 'Your stage name'),
(188, 'Repeat Password'),
(189, 'Register'),
(190, 'Recover password'),
(191, 'Featured Description'),
(192, 'Filter videos'),
(193, 'Most Commented Description'),
(194, 'Most Liked Description'),
(195, 'Most Viewed Description'),
(196, 'This video is not public!'),
(197, 'Please login or register to watch it'),
(198, 'Wrong username or password.'),
(199, 'Unfeature video'),
(200, 'Twitter login'),
(201, 'Check out this video'),
(202, 'Check this video'),
(203, 'Watch this video'),
(204, 'Blog'),
(205, 'Report not sent! Please make sure you complete all fields'),
(206, 'Report sent!'),
(207, 'Share a picture'),
(208, 'Choose an image:');


INSERT INTO `#dbprefix#options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES
(3, 'mediafolder', 'media', 'yes'),
(20, 'youtube-player', '0', 'yes'),
(5, 'jwkey', 'enaSseHIwj6O/Zpf3GPStcqpF6Ff2hjP8jRx/3GgYA8NY5k0ysqUuBQSlxRMJ4/p', 'yes'),
(6, 'choosen-player', '4', 'yes'),
(7, 'seo_desc', 'PHPVibe.', 'yes'),
(8, 'seo_title', 'PHPVibe ', 'yes'),
(9, 'site-logo', '', 'yes'),
(10, 'site-logo-mobi', 'Vibe', 'yes'),
(11, 'fb-fans', '0', 'yes'),
(12, 'fb-fans-checked', '0', 'yes'),
(13, 'fb-fanpage', '', 'yes'),
(14, 'video-width', '810', 'yes'),
(15, 'video-height', '456', 'yes'),
(16, 'video-coms', '0', 'yes'),
(17, 'related-nr', '16', 'yes'),
(18, 'bpp', '25', 'yes'),
(19, 'googletracking', '', 'yes'),
(21, 'site-logo-text', 'PHPVibe', 'yes'),
(22, 'videos-initial', '1', 'yes'),
(24, 'testing', 'testing good', 'yes'),
(25, 'update_options_now', '1', 'yes'),
(26, 'site-copyright', '© 2013 PHPVibe.com', 'yes'),
(27, 'tt', '1', 'yes'),
(28, 'cachedx', 'test', 'yes'),
(29, 'efe', 'efswef', 'yes'),
(30, 'def_lang', 'en', 'yes'),
(35, 'addthis', '1', 'yes'),
(36, 'googleanalitycs', '', 'yes'),
(37, 'uploadrule', '1', 'yes'),
(38, 'editrule', '1', 'yes'),
(39, 'soft', 'phpvibe', 'yes'),
(40, 'licto', 'Premium Video CMS', 'yes'),
(41, 'softc', 'UG93ZXJlZCBieSBwaHBWaWJlJnRyYWRlOy4=', 'yes'),
(42, 'Tw_Key', '', 'yes'),
(43, 'Tw_Secret', '', 'yes'),
(44, 'Fb_Key', '', 'yes'),
(45, 'Fb_Secret', '', 'yes'),
(46, 'allowfb', '0', 'yes'),
(47, 'allowtw', '1', 'yes'),
(48, 'allowlocalreg', '1', 'yes'),
(49, 'allowg', '1', 'yes'),
(50, 'COOKIEKEY', 'fg456', 'yes'),
(51, 'SECRETSALT', 'b81566', 'yes'),
(52, 'COOKIESPLIT', '-phpv-', 'yes'),
(53, 'jwp_version', '6', 'yes'),
(54, 'cron_lastrun', '0', 'yes'),
(55, 'cron_interval', '0', 'yes'),
(56, 'thumb-width', '205', 'yes'),
(58, 'lecheck', '1397405305', 'yes'),
(57, 'thumb-height', '114', 'yes'),
(59, 'upmenu', '1', 'yes'),
(60, 'musicmenu', '1', 'yes'),
(61, 'imagesmenu', '1', 'yes'),
(62, 'sharingrule', '1', 'yes'),
(63, 'mp3rule', '1', 'yes'),
(64, 'imgrule', '1', 'yes'),
(65, 'alext', 'flv,mp4,avi,mpeg', 'yes'),
(66, 'alimgext', 'png,gif,jpg,jpeg', 'yes'),
(67, 'ffmpeg-thumb-time', '00:00:03', 'yes'),
(68, 'maxup', '3145728000', 'yes'),
(69, 'importuser', '1', 'yes'),
(70, 'binpath', '/usr/bin/php', 'yes'),
(71, 'ffa', '0', 'yes'),
(72, 'ffmpeg-cmd', 'ffmpeg', 'yes'),
(73, 'ffmpeg-vsize', '640x360', 'yes'),
(74, 'tmp-folder', 'rawmedia', 'yes'),
(75, 'player-logo', 'uploads/pvl-png53451099ef4e7.png', 'yes'),
(76, 'Tw_Token', '', 'yes'),
(77, 'Tw_Tosecret', '', 'yes'),
(78, 'remote-player', '4', 'yes'),
(79, 'hide-mp4', '1', 'yes');
alter table #dbprefix#playlist_data add index playlist_idx (playlist);
alter table #dbprefix#users_friends add index uid_idx (uid);
alter table #dbprefix#users_friends add index fid_idx (fid);
alter table #dbprefix#ads add index ad_type_idx (ad_type);
alter table #dbprefix#ads add index ad_spot_idx (ad_spot);
alter table #dbprefix#crons add index cron_type_idx (cron_type);
alter table #dbprefix#videos add index views_idx (views);
alter table #dbprefix#videos add index dates_idx (date);
alter table #dbprefix#videos add index dates_idx (date(50));
alter table #dbprefix#videos add index pub_idx (pub);
alter table #dbprefix#videos add index source_idx (source(300));
alter table #dbprefix#videos add index tmp_source_idx (tmp_source(300));
alter table #dbprefix#users add unique email_uni (email);
alter table #dbprefix#options add unique option_name_uni (option_name);
alter table #dbprefix#likes add unique uid_uni (uid, vid);